import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ProfileModal } from '../components/ProfileModal' 
const Home: NextPage = () => {
  return (
    <div className="relative w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-2xl font-bold text-center">Hello</h1>
      <ProfileModal/>
    </div>
  );
};

export default Home;
